from class_implementation.DBClass import DataBase

db = DataBase()
db.select_db()
# db.create_db(database="proj_extensao")

# select_db = """
#   USE projeto_estacio;
# """

# db.execute_query("select_db", query=select_db)

insert_aluno = """
INSERT INTO `aluno` (`cpf`,`nome`,`idade`,`sexo`,`celular`,`curso`,`turno`) 
VALUES 
('MDEzMTUzMzk2NzY=','Tmljb2xlIElzYWJlbGxhIFBlcmVpcmE=',19,'F','MzE5OTY3NjAzNzc=','LEGISLAÇÃO DE TRÂNSITO','M'),
('MjU4ODU1MzE2ODQ=','TeFyY2lvIENhbGViIFRoYWxlcyBQaXJlcw==',28,'M','MzU5ODQ0ODY2NDI=','EQUIPAMENTOS OBRIGATÓRIOS','T'),
('MTc2MTgyNjk2NDU=','Q2FtaWxhIE5pY29sZSBDbGFyYSBBcGFy7WNpbw==',26,'F','MzE5ODQ2ODc5MzE=','DIREÇÃO DEFENSIVA','T'),
('MTM0MTc4Njg2Mjk=','VGVyZXNpbmhhIEx1bmEgRmFyaWFz',25,'F','MzE5ODcyMzg0MzA=','LEGISLAÇÃO DE TRÂNSITO','T'),
('MTQ1NTg5Mzc2NTI=','U/RuaWEgQWxpY2UgR2FicmllbGx5IENhbXBvcw==',25,'F','MzE5OTI3NjAxOTc=','EQUIPAMENTOS OBRIGATÓRIOS','T'),
('MzExNzg5NjU2Mjc=','WWFzbWluIElzYWJlbGxhIFRlcmV6YSBQaW50bw==',23,'F','MzE5ODkwMDgyNTU=','MEIO AMBIENTE','M'),
('MzMyMzI1ODM2MzY=','WXVyaSBGZXJuYW5kbyBMaW1h',69,'M','MzQ5OTkyNjgzMTY=','DIREÇÃO DEFENSIVA','N'),
('MzQ2NTk5Mjg2NTk=','QW5kcmVhIE1hcmlhIElzaXMgZGEgQ29zdGE=',23,'F','MzE5ODYyMTAyODk=','EQUIPAMENTOS OBRIGATÓRIOS','M'),
('MzQyMzE5MzQ2ODE=','TGV2aSBFZHNvbiBUb23hcyBkYSBSb3Nh',44,'M','MzQ5OTMzMDU2NjU=','MEIO AMBIENTE','M'),
('MzU1Mjk3NzU2MjQ=','S2V2aW4gSGVucnkgQXNzdW7n428=',32,'M','MzE5OTU5Njg5NjY=','DICAS E MACETES','T'),
('MzY1Nzc0NzU2Nzk=','U2FicmluYSBBbmRyZWEgRm9nYedh',30,'F','MzE5OTg4MTI0Nzc=','DIREÇÃO DEFENSIVA','M'),
('MzY4NzgyNTU2NjA=','R2FlbCBQZWRybyBWaWFu',32,'M','MzE5OTYzNzA5OTA=','LEGISLAÇÃO DE TRÂNSITO','N'),
('NDc3NDE4NTU2NjI=','RW5yaWNvIEJlcm5hcmRv',41,'M','MzE5ODQ2ODc5MzE=','EQUIPAMENTOS OBRIGATÓRIOS','T'),
('NDI4MzMyMTU2NzM=','SXNhYWMgUmVuYXRvIEhlbnJ5IFJlemVuZGU=',40,'M','MzU5OTQxNjM3Nzc=','EQUIPAMENTOS OBRIGATÓRIO','T'),
('NDM5MzEwMDk2NDU=','Sm9hcXVpbSBCZW7tY2lvIENhbGViIEFyYfpqbw==',45,'M','MzE5OTkyNDE1ODE=','LEGISLAÇÃO DE TRÂNSITO','T'),
('NDQ4NDM2OTg2OTU=','TeFyaW8gTmVsc29uIElzYWFjIGRhcyBOZXZlcw==',35,'M','MzE5OTc4MTExNjM=','DIREÇÃO DEFENSIVA','T'),
('NDU3Njk5OTM2MjY=','TWFyaWFoIE1hbHUgU2FuZHJhIER1YXJ0ZQ==',22,'F','MzE5OTQ4OTI2NTA=','EQUIPAMENTOS OBRIGATÓRIOS','T'),
('NjgzNzc5MzI2ODc=','UGlldHJvIENhdeMgTGVhbmRybyBDYXZhbGNhbnRp',19,'M','MzE5OTY2ODk5MTU=','LEGISLAÇÃO DE TRÂNSITO','T'),
('Njk5OTE1ODA2MTE=','Q2F14yBLYXXqIFNhbnRvcw==',55,'M','MzE5ODQ2ODc5MzE=','DIREÇÃO DEFENSIVA','T'),
('NjkzODUwNzE2Mzc=','UmViZWNhIEZhYmlhbmEgZGEgQ3VuaGE=',45,'F','Mzg5ODU3MjYxNjg=','LEGISLAÇÃO DE TRÂNSITO','T'),
('NjU1ODEwMTM2MDg=','TGl6IEFsbGFuYSBTb3V6YQ==',18,'F','MzE5OTUyNDcxNDY=','MEIO AMBIENTE','M'),
('NTc3NzI1OTQ2NDA=','SWFnbyBHYWVsIFZpdG9yIFZpYW5h',19,'M','MzE5ODQ2ODc5MzE=','MEIO AMBIENTE','N'),
('NTc4NzkxNTY2NjY=','Sulzc2ljYSBTb3BoaWUgTGHtcyBWaWVpcmE=',27,'F','MzE5OTcxMDE2MTI=','MEIO AMBIENTE','N'),
('NTE1NzQ4MjM2MTI=','Sm9yZ2UgQWxleGFuZHJlIEVtYW51ZWwgUm9kcmlndWVz',27,'M','MzE5OTc2NTY4MDM=','DIREÇÃO DEFENSIVA','T'),
('NTE3MDE1MDY2MDI=','U2ViYXN0aeNvIExlYW5kcm8gRmVycmVpcmE=',45,'M','MzE5ODU2MDAzNzU=','LEGISLAÇÃO DE TRÂNSITO','M'),
('NTEyMDgyMTc2NjY=','THVjYXMgQnJ5YW4gTWF0aGV1cyBCcml0bw==',36,'M','MzE5OTU0MjQ4OTg=','MEIO AMBIENTE','M'),
('NTI0MTQyMjc2NTY=','SXNhYmVsYSBCZWF0cml6IFJlZ2luYSBDYXJ2YWxobw==',27,'F','MzI5ODcyMjg3OTY=','EQUIPAMENTOS OBRIGATÓRIOS','M'),
('NTY4MDg0ODg2NDk=','QW50b25lbGxhIEVsaXNhIEFuZHJlYQ==',23,'F','MzE5OTc2MDY5Mjg=','EQUIPAMENTOS OBRIGATÓRIOS','M'),
('NzgzNzU1NTI2MDc=','R2FicmllbGEgTGl6IEZvZ2HnYQ==',19,'F','MzE5OTE3NTkwNjg=','LEGISLAÇÃO DE TRÂNSITO','N'),
('NzI4OTMxMDI2ODk=','VmluaWNpdXMgSGVpdG9yIFJlbmF0byBSYW1vcw==',32,'M','MzE5OTUyMjYyMTY=','DICAS E MACETES','T'),
('ODg4MTQ4OTM2ODM=','T2xpdmlhIEhlbGVuYSBNYXJpbmEgQ29ydGUgUmVhbA==',34,'F','Mzc5OTIxODA0Nzc=','LEGISLAÇÃO DE TRÂNSITO','T'),
('ODk5OTg2MjU2OTY=','TO12aWEgUmFmYWVsYSBGZXJuYW5kZXM=',20,'F','MzE5ODQ2ODc5MzE=','MECÂNICA BÁSICA','N'),
('ODY5NTM2NDI2NzA=','TGF1cmEgQW5hIFBpZXRyYSBNb3JhZXM=',23,'F','MzQ5ODE2MzQwMDU=','LEGISLAÇÃO DE TRÂNSITO','M'),
('OTM1ODU2Nzk2MTc=','TGV2aSBNaWd1ZWwgUGF1bG8gTm92YWVz',34,'M','MzE5OTUyOTIzNzk=','DICAS E MACETES','N');
"""

db.execute_query("insert_aluno", query=insert_aluno) 
